Feature/transactions
bregnvig/F2020 pull request #6
Opened 2020-03-31 19:44 UTC by mbart71

New mysql mapping

2020-04-02 15:38 UTC, bregnvig requested changes

2020-04-02 15:38 UTC, bregnvig commented on apps/builder/src/app/mysql/mysql.config.ts
> +  });
Du skal nok have dit pw ud af koden vi har i et åbent repo

2020-04-02 21:53 UTC, mbart71 commented on apps/builder/src/app/mysql/mysql.config.ts
> +  });
removed

2020-04-04 13:40 UTC, bregnvig approved these changes

2020-04-04 13:46 UTC, merged